### ISSUE TITLE
c128 version?

### ISSUE THREAD

**Issue by xlar54** [nanoflite/c64-up2400-cc65#2]
Not sure how to access this or the userport from 128 mode

**Comment by nanoflite** [comment]
They both use the same address $DD00, so it should be possible to use from C128 in 128 mode. I have not done this myself though. Probably some changes are needed?

**Comment by xlar54** [comment]
yeah, i see some routines which are in a different location on the 128.  But even so, the 128 can do 2400 without this, so I will close this issue.
